import random

# Pete's embarrassment of riches 🏋️
# Split into categories so we can sprinkle variety
MOTIVATIONAL = [
    "Consistency is queen, volume is king!",
    "No pain, champagne!",
    "Every rep is rent — and you’re paying on time.",
    "Discipline: the only PR that matters.",
    "You don’t find time, you grind time.",
    "Flex today, flex tomorrow, flex forever.",
    "Failure isn’t the end, it’s just the warm-up set.",
    "The iron never lies — but it does flirt.",
    "Sets build strength, but sweat builds character.",
    "You are the barbell, and the world is just the rack.",
    "Strength isn’t given, it’s squatted.",
    "You’re stronger than yesterday’s excuses.",
    "Reps build resilience.",
    "Work ethic: the heaviest weight in the room.",
    "Train insane or remain the same.",
    "Your warmup is someone else’s workout.",
    "Pain is weakness leaving the spreadsheet.",
    "Muscle is earned, not Amazon Primed.",
    "Winners don’t skip leg day.",
    "No excuses, just endorphins.",
    "Your lungs are just squat racks for oxygen.",
    "The grind doesn’t stop, it just reracks.",
    "The barbell is your confession booth.",
    "Sweat is the body’s autograph.",
    "Each PR is a postcard from the future.",
    "Squats cure sadness 9 times out of 10.",
    "Push harder, Pete believes in you.",
    "Your gym card is a passport to greatness.",
    "You don’t stop when you’re tired, you stop when Pete claps.",
    "Endorphins don’t lie.",
    "Your DOMS today is your swagger tomorrow.",
    "Beast mode isn’t a switch, it’s a lifestyle.",
    "Your body can, your mind must.",
    "You don’t lift weights, you lift yourself.",
    "Sweat equity always pays dividends.",
    "No bar too heavy, no excuse too light.",
    "Sore today, legend tomorrow.",
    "You can’t spell hustle without U.",
    "Strength is rented, not owned.",
    "Pete’s law: every day is arm day somewhere.",
    "Train hard, stay humble, eat carbs.",
    "Rest when you’re done, not when you’re tired.",
    "Progress, not perfection.",
    "Reps and sets, debts and bets.",
    "No PR comes from comfort.",
    "Every plate is a stepping stone.",
    "Dreams don’t lift themselves.",
    "Make sweat your currency.",
    "Your warm-up is someone else’s peak.",
    "Motivation gets you started, Pete keeps you going.",
    "Gains are made in the margins.",
    "Intensity builds identity.",
    "Your only rival is yesterday’s you.",
    "Repetition builds reputation.",
    "Muscle: the ultimate side hustle.",
    "Flexecution is the goal.",
    "Your limits are suggestions.",
    "Breathe discipline, exhale progress.",
    "Pete’s truth: gravity is optional.",
    "Strength is a choice you make daily.",
    "Leg day = therapy session with weights.",
    "The barbell is the ultimate therapist.",
    "No cardio, no crydio.",
    "Endurance is just stubbornness with sneakers.",
    "One more rep, one more victory.",
    "Comfort zones don’t build quads.",
    "Grind, shine, repeat.",
    "You don’t count reps, reps count you.",
    "Every drop of sweat is an IOU to success.",
    "Your PRs are proof of existence.",
    "Leg day is democracy in action.",
    "Volume today, power tomorrow.",
    "Push until the mirror nods back.",
    "Strength doesn’t come from mirrors, it comes from racks.",
    "The gym is the forge, you’re the iron.",
    "Sweat is your down payment on greatness.",
    "Barbells speak louder than words.",
    "No deadlift, no destiny.",
    "Push harder — Pete’s watching.",
    "Consistency carves statues.",
    "Your body is your legacy.",
    "Gym time is prime time.",
    "The grind doesn’t clock out.",
    "No rerack without respect.",
    "Earn your endorphins.",
    "Work harder than your reflection.",
    "The gym floor is holy ground.",
    "Progress is pain’s pretty cousin.",
    "No goals, no glory.",
    "Squats > therapy.",
    "Failure is just data for the comeback.",
    "More sweat, less regret.",
    "Muscle is momentum.",
    "Your next PR is already inside you.",
    "Squats are poetry, deadlifts are novels.",
    "Pull harder — the earth owes you.",
    "Train for today, flex for tomorrow.",
    "The grind has no off-season.",
    "Sweat is the soul’s cologne.",
    "No PR? No problem. Pete’s still proud.",
    "Bench like your future depends on it.",
    "Rest is a weapon, not an excuse.",
    "Pete’s truth: one more rep always fits.",
    "Strength doesn’t skip breakfast.",
    "DOMS: Delayed Onset Motivation Syndrome.",
    "Leg day builds patience, deadlifts build rage.",
    "You don’t quit, you rerack.",
    "Your lungs are engines, fuel them.",
    "Every plank builds character.",
    "Biceps are currency, squats are credit.",
    "Progress doesn’t come in comfort.",
    "The grind pays better than crypto.",
    "Deadlifts never ghost you.",
    "Pete’s motto: never miss a Monday.",
    "The pump is the truth.",
    "Sweat is the ink, reps are the story.",
    "No cardio, no confidence.",
    "Your quads write cheques your jeans can’t cash.",
    "Your strength is louder than your doubts.",
    "No bar too loaded, no spirit too light.",
    "Every burpee is a love letter to chaos.",
    "Caffeine and iron, the breakfast of champions.",
    "You can’t download strength.",
    "The grind is non-refundable.",
    "You’re a rep factory.",
    "Strength > speed > excuses.",
    "Progress is patient.",
    "Every PR is Pete-approved.",
    "Legends are squatted, not born.",
    "Your excuses expired yesterday.",
    "Endorphins are nature’s applause.",
    "Lift like nobody’s judging.",
    "Sweat equity is undefeated.",
    "Pete’s gospel: squats save souls.",
    "Gym time is truth time.",
    "Progress is inevitable, if you don’t quit.",
    "The grind is your gift to yourself.",
    "Don’t wait for inspiration, be your own motivation.",
    "You don’t chase gains, you attract them by showing up.",
]

SILLY = [
    "Hakuna matata reps!",
    "Rome wasn’t foam-rolled in a day.",
    "Cardio-bardi flow state.",
    "Plank Sinatra vibes.",
    "Protein shake, not protein fake.",
    "Don’t squat the small stuff.",
    "Burpees? More like slurpees.",
    "Abs-olutely fantasmic.",
    "Brotein overload incoming!",
    "Your macros called — they’re lonely.",
    "Foam roll with it, baby.",
    "Bench you later, alligator.",
    "Deadlift and let lift.",
    "Curls for the girls, deads for the dads.",
    "Sweat like nobody’s watching.",
    "Flexpect the unexpected.",
    "Absurd abs incoming.",
    "Get swole or get strolled.",
    "Gymtimidation is cardio for the soul.",
    "Dumbbell doors to destiny.",
    "Spot me like you spotted Bigfoot.",
    "Protein-shake it off.",
    "Lats Christmas I gave you my reps.",
    "Burpocalypse Now.",
    "Flex Luther King Jr.",
    "The walking quad.",
    "Foam and fortune.",
    "Dumbbellina ballerina.",
    "Treadmill of fortune.",
    "Pec-tacular party.",
    "Squat you looking at?",
    "Kettle-smell, but in a good way.",
    "Abscond with abs.",
    "Core-blimey!",
    "Gym and tonic.",
    "Curl Jam.",
    "Swole patrol.",
    "Benchaholic anonymous.",
    "Goblet of swole.",
    "Plank you very much.",
    "Lat-er, bro.",
    "Pushup and away!",
    "Squad goals = squat goals.",
    "Burpee-di-bop-di-boo.",
    "Biceps and rice.",
    "Shakes and ladders.",
    "Gymfinity and beyond!",
    "Sweatflix binge.",
    "The Abfather.",
    "Harry Squatter.",
    "Load of quads.",
    "Grip it and rip it.",
    "Barbell-hop anonymous.",
    "Hammies of destiny.",
    "Six-pack attack.",
    "Captain Core-ageous.",
    "Deltoid delight.",
    "Mo’ reps, mo’ problems.",
    "Hip-thrust-a-licious.",
    "Snaccident: ate a whole protein bar.",
    "Fleece the quads.",
    "The tricep whisperer.",
    "Beefcake bakeoff.",
    "Curl friends forever.",
    "Lunge life balance.",
    "All gain, no grain.",
    "Sweatflix and chill.",
    "Rogue one-rep max.",
    "Squatalicious.",
    "Glute flute symphony.",
    "Absurdly ab-firmative.",
    "Protein princess diaries.",
    "Lats supper.",
    "Flextra-terrestrial.",
    "Foam alone.",
    "Benchpressaurus rex.",
    "Brodo Baggins and the Lord of the Gains.",
    "Deadlifty McDeadface.",
    "The Fast and the Furriest (sled pushes).",
    "Reptacular fiesta.",
    "Hamstring hammertime.",
    "Cable guy workout edition.",
    "Pull-up Palooza.",
    "Legs Miserables.",
    "The Hunger Gains.",
    "Pushupocalypse now.",
    "Return of the quadri.",
    "Sweat dreams are made of these.",
    "Row row row your gains.",
    "Squat happens.",
    "Foam roller derby.",
    "Absurdistan core workout.",
    "Calf-ternoon delight.",
    "The glute crew review.",
    "Bench and the Beast.",
    "Barbellissimo!",
    "The Lord of the Rings (pull-ups).",
    "Mission ab-possible.",
    "Titanic triceps.",
    "Pec-toberfest.",
    "The floor is quad lava.",
    "Get ripped or cry tryin’.",
    "Protein Potter and the Chamber of Swolesecrets.",
    "Shredded wheat but human.",
    "Brodozer incoming.",
    "Swole Wars: The Rep Awakens.",
    "Squatronauts.",
    "Shoulder shrug life.",
    "Beard gains and barbells.",
    "Pete and repeat, but with reps.",
    "The quads of March.",
    "T-Bar-bie workout edition.",
    "Resistance is futile — except in training.",
    "Absurdistan bootcamp.",
    "Snatch-topus arms.",
    "Gym Reaper strikes again.",
    "Caffeine and creatine, baby.",
    "Leg-o-my-ego squats.",
    "Flexecution squad assemble!",
    "Call of Booty (hip thrusts).",
    "Mile high plyo club.",
    "The plank tank.",
    "Gymbo slice.",
    "Protein Picasso.",
    "Shake weights and heartbreaks.",
    "Captain Jacked Sparrow.",
    "Quadzilla vs. Hamstring Kong.",
    "Swolemates forever.",
    "Gripocalypse.",
    "Cardi-no thanks-o.",
    "Bench-o-rama-ding-dong.",
    "Sweaty spaghetti.",
    "Gymshort stories.",
    "Protein palooza.",
    "Flex-capade.",
    "The cardio carnival.",
    "Biception.",
    "Protein in motion.",
    "Row-bocop.",
    "Flex McMuscleface.",
    "Absurdly swole science.",
    "Triceptacular.",
    "The cable chronicles.",
    "Kettle-bro conundrum.",
    "Sweatnado.",
    "Caffeine crusaders.",
    "Iron throne gains.",
    "Quad squad forever.",
    "Flex Machina.",
    "Brofessor Pete, PhD in PRs.",
    "Lift long and prosper.",
    "Chewbacca shrugs.",
    "Protein, plank, repeat.",
    "Swoldemort returns.",
    "The great glute bake-off.",
    "Kettle-bellissimo.",
    "Planktopus Prime.",
    "Absurdopolis leg day.",
    "Flexaholic anonymous.",
    "Hammie jammy jazzercise.",
    "Lungemania madness.",
    "Deadlift deli special.",
    "Sweat roulette.",
    "Cardio karaoke.",
    "Dumbbell derby day.",
    "Protein pumpkin spice latte gains.",
    "The lunge lounge.",
    "Cable chaos carnival.",
    "Absurdonomics of sweat.",
    "Burpee bonanza.",
    "Foam-tastic voyage.",
    "Bench-a-palooza.",
    "Gains of Thrones.",
    "Protein pretzel logic.",
    "Shake, rattle, and reps.",
    "Flexytown express.",
    "Abs-anity asylum.",
    "Quadcast podcast.",
    "Rowmageddon.",
    "The pec-tacular spectacle.",
]

PORTMANTEAUS = [
    "Squattastic flexcellence!",
    "Deadliftacular!",
    "Glutetopia awaits!",
    "Push-upocalypse now.",
    "Curlnado.",
    "Lungemageddon.",
    "Flexocalypse.",
    "PR-arama.",
    "Cardiovangelist crusade.",
    "Burpeepocalypse.",
    "Benchtacular bonanza.",
    "Snatchzilla.",
    "Flexstravaganza.",
    "Hamstringageddon.",
    "Quadzilla quest.",
    "Delttastrophe.",
    "Calfpocalypse.",
    "Endorphinvasion.",
    "Maxoutathon.",
    "Chinupocalypse.",
    "Sweatnado.",
    "Rowmageddon.",
    "Plankopalooza.",
    "Caffeinepocalypse.",
    "Abstravaganza.",
    "Lungopalooza.",
    "Repocalypse.",
    "Gaintopia.",
    "Proteinpalooza.",
    "Domspocalypse.",
    "Flexsasterpiece.",
    "Triceptacular.",
    "Squatmaggedon.",
    "Pullupalooza.",
    "Musclemageddon.",
    "Cardiopalooza.",
    "Brodown showdown.",
    "Swolemania.",
    "Grindageddon.",
    "Legstacular.",
    "Curlocalypse.",
    "Benchzilla.",
    "Liftocalypse.",
    "Gainsquake.",
    "Repzilla.",
    "Domstacular.",
    "Flexpocalypse.",
    "Hamstapalooza.",
    "Abzilla.",
    "Pushupalypse.",
    "Snatchquake.",
    "Sweattastrophe.",
    "Rowzilla.",
    "Liftoffopalooza.",
    "Pullupocalypse.",
    "Gainsplosion.",
    "Cardiocalypse.",
    "Plankzilla.",
    "Deadliftocalypse.",
    "Proteinageddon.",
    "Swolequake.",
    "Abmageddon.",
    "Flexathon.",
    "Legquake.",
    "Curlstorm.",
    "Benchageddon.",
    "Hamstringopalooza.",
    "Maxoutocalypse.",
    "Tricepzooka.",
    "Quadquake.",
    "Sweatstorm.",
    "Liftoholics anonymous.",
    "Domstocalypse.",
    "Flexquake.",
    "Gainsplosion express.",
    "Rowpocalypse.",
    "Absquake.",
    "Brocalypse.",
    "Swolecalypse.",
    "Flexival.",
    "Lungequake.",
    "Endorphinzilla.",
    "Bicepsplosion.",
    "Reptastrophe.",
    "Cardioquake.",
    "Squatstorm.",
    "Plankageddon.",
    "Snatchmageddon.",
    "Sweatquake.",
    "Proteinopalooza.",
    "Glutequake.",
    "Triceptageddon.",
    "Pullupquake.",
    "Liftoquake.",
    "Repstorm.",
    "DOMSpalooza.",
    "Gainstorm.",
    "Curlopalooza.",
    "Maxzilla.",
    "Benchstorm.",
    "Hamquake.",
    "Absopalooza.",
    "Flexzilla.",
]

METAPHORS = [
    "That set was thicker than a January protein shake.",
    "You attacked that bar like a lion chasing gazelles with gym memberships.",
    "Those squats were deeper than Shakespeare’s sonnets.",
    "You ran like cardio owed you money.",
    "You pressed like the floor was gossip and you had tea to spill.",
    "Your RDLs are straighter than a nun’s ruler.",
    "You slept like a hibernating kettlebear.",
    "Your steps were higher than Pete Davidson’s dating roster.",
    "You benched like a trebuchet at a medieval arm day.",
    "You pulled like gravity was just a polite suggestion.",
    "Your VO₂ max just filed for divorce — it can’t keep up with you.",
    "You sprinted like the treadmill was repossessing your shoes.",
    "Those lunges were more dramatic than a soap opera finale.",
    "Your curls had more drama than a Bravo reunion.",
    "You foam rolled like you were flattening croissants.",
    "Sleep score so high you’re basically a mattress salesman.",
    "Those calories didn’t stand a chance — you hunted them down like prey.",
    "You hydrated like an Amazon rainforest.",
    "PRs fell like dominoes in a CrossFit box.",
    "Your core was tighter than a drum at a rock concert.",
    "You rowed like Poseidon was your spotter.",
    "You squatted like Atlas after a double espresso.",
    "You benched like the earth itself needed pressing.",
    "You deadlifted like gravity had a personal vendetta.",
    "Your planks were sturdier than medieval drawbridges.",
    "You moved kettlebells like Thor misplaced his hammer.",
    "You sprinted like your Uber Eats driver was outside.",
    "Your pull-ups soared higher than inflation.",
    "You shrugged like Atlas dropping the globe.",
    "Those step counts were wilder than a TikTok dance trend.",
    "You squatted like democracy depended on it.",
    "That deadlift had more suspense than a Netflix thriller.",
    "Your calories burned brighter than a bonfire at Glastonbury.",
    "You trained harder than a Rocky montage marathon.",
    "You slept like you were auditioning for a mattress ad.",
    "That lunge was longer than the Lord of the Rings trilogy.",
    "Your sweat flowed like Niagara Falls in August.",
    "You curled like the stock market in a recession.",
    "Your push-ups were sharper than a chef’s knife set.",
    "You flexed like a Greek statue on payday.",
    "You ran like cardio was your side hustle.",
    "You hip-thrusted like the glutes had a vendetta.",
    "That plank lasted longer than a Marvel end-credit scene.",
    "You benched like a trebuchet hurling medieval gossip.",
    "Your sprints were more intense than a Black Friday sale.",
    "You hydrated like an overwatered cactus.",
    "Your quads roared louder than a V8 engine.",
    "You lifted like rent was due and plates were the currency.",
    "Your hamstrings twanged like rock guitar solos.",
    "You squatted lower than bank interest rates.",
    "That deadlift was smoother than jazz on a Sunday.",
    "You pressed like Zeus himself was watching.",
    "You rowed harder than Vikings late for a raid.",
    "Your endurance ran longer than Pete’s catchphrase list.",
    "You recovered like Wolverine on cheat day.",
    "You flexed like the cover of Muscle Monthly.",
    "That RDL was straighter than an honour student’s posture.",
    "Your steps marched like a Roman legion.",
    "You lunged across time zones.",
    "That squat shook tectonic plates.",
    "You benched like a power plant.",
    "Your planks had more tension than a boardroom coup.",
    "You pulled harder than Brexit negotiations.",
    "That curl was juicier than fresh gossip.",
    "Your sets were bigger than box office hits.",
    "You jumped like gravity was optional.",
    "You rowed like you were escaping Mordor.",
    "Your squats dropped lower than SoundCloud rap.",
    "That deadlift was more gripping than a horror movie.",
    "You burned calories like arson.",
    "You pressed like the morning snooze button owed you money.",
    "You ran like Forrest on a deadline.",
    "That push-up had more drama than Shakespeare in tights.",
    "You sprinted faster than a student after free pizza.",
    "Your sets banged louder than festival basslines.",
    "You flexed harder than tax season.",
    "That recovery was deeper than therapy.",
    "Your deadlifts hit harder than a bass drop.",
    "You slept harder than a narcoleptic bear.",
    "Your PR slapped harder than Pete’s metaphors.",
    "Those steps marched longer than a Taylor Swift setlist.",
    "You rowed harder than Oppenheimer’s conscience.",
    "Your core was tighter than skinny jeans at brunch.",
    "That curl was sweeter than a protein donut.",
    "You gripped that bar like an angry koala.",
    "Your lunges were more dramatic than reality TV.",
    "You pressed harder than a stuck elevator button.",
    "That squat cracked more ground than a geological survey.",
    "You sprinted like rent was chasing you.",
    "Your bench bounced harder than a payday check.",
    "That RDL was straighter than my taxes.",
    "You flexed harder than a Marvel casting call.",
    "That hydration was wetter than British weather.",
    "Your endurance outlasted Game of Thrones filler.",
    "That deadlift was darker than Pete’s sense of humour.",
    "You planked like tectonic plates in a standoff.",
    "Your sweat flowed like a Taylor Swift breakup album.",
    "That pull-up was higher than Bezos’ rocket.",
    "Your sets hit harder than Shakespeare in a cage fight.",
    "You ran longer than a conference call rant.",
    "That squat was heavier than student debt.",
    "You benched like the floor was made of trampolines.",
    "That curl was cleaner than new sneakers.",
    "You pressed like it was the last day on earth.",
    "You rowed with more force than Brexit papers.",
    "That sprint outran gossip itself.",
    "Your plank held tighter than family secrets.",
    "That PR exploded louder than fireworks on NYE.",
    "You flexed brighter than a disco ball.",
    "That lunge crossed time itself.",
    "Your sweat wrote history in salt.",
    "That bench was louder than stadium chants.",
    "You rowed like the ocean was personal.",
    "Your quads stomped harder than Godzilla in heels.",
    "That recovery was smoother than butter coffee.",
    "You sprinted sharper than caffeine jitters.",
    "Your hamstrings twanged like violin strings.",
    "That deadlift was heavier than Monday mornings.",
    "You benched like you were printing money.",
    "That set had more suspense than Stranger Things.",
    "You pulled like the earth owed you gravity.",
    "That plank was stiffer than British upper lips.",
    "You curled like you were rewriting genetics.",
    "That squat was bigger than the Big Bang.",
    "You flexed brighter than a Christmas tree in Vegas.",
    "Your PR echoed like a stadium roar.",
    "That RDL was straighter than a laser pointer.",
    "You rowed like a Viking Uber.",
    "Your sprints were hotter than July pavements.",
    "That hydration was wetter than a water park.",
    "Your bench was more uplifting than a TED talk.",
    "That push-up was tighter than skinny jeans.",
    "You pressed like Zeus on creatine.",
    "That deadlift rewrote gravity.",
]

COACHISMS = [
    "Glutes to the moon 🚀",
    "Hydration station, all aboard!",
    "Core tight, future bright.",
    "Recovery is just training in disguise.",
    "Sweat equity: the only crypto that never crashes.",
    "Macros are the new horoscopes.",
    "Hamstrings of destiny.",
    "Hydrate or diedrate.",
    "Eat clean, lift dirty.",
    "Gym hair, don’t care.",
    "Rest days are secret growth days.",
    "Your biceps are RSVP’d to the gun show.",
    "Leg day: democracy in action.",
    "Bench press: the chest’s autobiography.",
    "Squats pay the rent, deadlifts pay the mortgage.",
    "Carbs are friends, not enemies.",
    "Warm up like you mean it, cool down like you earned it.",
    "Every foam roll is a love letter to tomorrow’s mobility.",
    "Stretch like you’re auditioning for Cirque du Soleil.",
    "Pete believes in you, even when your hamstrings don’t.",
    "Never trust a man who skips leg day.",
    "Your mirror is lying — but the barbell tells the truth.",
    "Cardio is just patience practice.",
    "Protein shakes taste better with victory.",
    "Always rack your weights, even if life won’t rack itself.",
    "A PR a day keeps the doctor away.",
    "Deadlifts cure sadness. Temporarily.",
    "Pete’s gospel: squats save souls.",
    "Biceps are the hello, triceps are the goodbye.",
    "Every gym bag is a suitcase of dreams.",
    "Shoes off, gains on.",
    "The foam roller is cruel but fair.",
    "Protein is the duct tape of the body.",
    "Caffeine is pre-workout for the soul.",
    "Abs are made in the kitchen, revealed in the squat rack.",
    "You can’t flex excuses.",
    "Barbells > Barbies.",
    "Every rep is an affirmation.",
    "Respect the rest, respect the reps.",
    "Stretch now, thank yourself later.",
    "The warm-up is the workout’s handshake.",
    "Sweat is just confidence leaking.",
    "If you can talk, you can do another rep.",
    "Lifting is therapy; therapy doesn’t give you traps.",
    "Friends don’t let friends skip deadlifts.",
    "No squat, no respect.",
    "Foam roll or face the consequences.",
    "Hydration before hydration.",
    "PRs are the universe applauding.",
    "A set unfinished is a story untold.",
    "Machines don’t build men, but men build on machines.",
    "The scale is negotiable, the barbell is not.",
    "Calories are opinions, reps are facts.",
    "Every plank is a promise.",
    "Stretch like you’ve got all the time in the world.",
    "Recovery is free muscle.",
    "Dumbbells are friends with handles.",
    "Strength is contagious — spot generously.",
    "You don’t need luck, you need lunges.",
    "The squat rack is the church of iron.",
    "Sweat now, swagger later.",
    "Barbells don’t ghost you.",
    "If it jiggles, it just wants more squats.",
    "Rest days are anabolic investments.",
    "Hydration is holy.",
    "Stretching is aging backwards.",
    "Your warm-up should make you sweat.",
    "You can’t spell cardio without crying.",
    "Abs aren’t for looks, they’re for laughs.",
    "Spot others the way you want to be spotted.",
    "Machines for precision, barbells for poetry.",
    "Pete’s law: sweat is thicker than water.",
    "Flexing is free advertising.",
    "Don’t fear failure; fear missing a rep.",
    "If the shoe fits, it’s probably flat-soled.",
    "Macros > astrology.",
    "Leg day loyalty test.",
    "Every lunge is a love letter to balance.",
    "Hydrate until your pee is Instagrammable.",
    "Stretching is soul floss.",
    "Core is king, glutes are the crown.",
    "Protein before nonsense.",
    "Your triceps tell the story of your past.",
    "Curls are punctuation for your sentences.",
    "The bench is the diary of your chest.",
    "Quads are democracy in action.",
    "Sweat is the gym’s incense.",
    "Recovery naps are anabolic magic.",
    "Carbs fuel the engine, protein builds the engine.",
    "Hydration: the cheapest supplement.",
    "Squats are honesty tests.",
    "If Pete claps, you’re not done.",
    "Stretch until your excuses leave.",
    "DOMS = proof you exist.",
    "A rep skipped is a debt unpaid.",
    "Foam rollers are medieval torture devices — use them.",
    "Lifting with Pete is like praying with iron.",
    "Hydration station never leaves the tracks.",
    "Every dumbbell has a destiny.",
    "Sweat equity compounds interest.",
    "Protein shakes > milkshakes.",
    "Macros matter more than gossip.",
    "Squat like your ancestors are watching.",
    "Recovery isn’t lazy; it’s proactive lifting.",
    "Every PR is sacred.",
    "Abs are just the receipts for good behaviour.",
    "Weights don’t cheat, but they make you honest.",
    "Stretching = maintenance for your chassis.",
    "Pete’s rule: plates before dates.",
    "Hydration cures 90% of your problems.",
    "Spotting is love in action.",
    "Rest now, lift later, flex forever.",
    "Never underestimate the triceps.",
    "Flexing burns calories (technically).",
    "You can’t spell strength without sweat.",
    "Gym time is me time, and me time is swole time.",
    "Recovery today, domination tomorrow.",
    "Glutes > excuses.",
    "No gym, no peace.",
    "PRs > arguments.",
    "Deadlifts = diplomacy.",
    "Sleep like a champion, wake like a legend.",
    "Stretch like a rubber band of destiny.",
    "Leg day separates lifters from tourists.",
    "Carbs are hugs for your muscles.",
    "If you fail, fail forward with a barbell.",
    "Spot strong, spot safe.",
    "Sweat equity is Pete’s economy.",
]

# Combine them all into one mega-pile
ALL_PHRASES = MOTIVATIONAL + SILLY + PORTMANTEAUS + METAPHORS + COACHISMS

# Legendary easter eggs – Pete’s ultra-rare sayings
LEGENDARY = [
    "🏆 You’ve unlocked Beast Mode DLC.",
    "🍕 Cheat day approved by Pete — order pizza immediately.",
    "🦄 You squatted so deep you found Narnia.",
    "☠️ Cardio killed me, you’re on your own.",
    "📈 Your quads have gone public — NASDAQ ticker: SQUAT.",
    "🎸 Deadlifts heavier than Metallica’s back catalogue.",
    "🦍 Gains so strong Darwin wants a word.",
    "🚑 DOMS level: hospital wing at Hogwarts.",
]

def random_phrase(kind="any", mode="balanced") -> str:
    """
    Pick a random phrase from Pete's arsenal.
    kind can be: motivational, silly, portmanteau, metaphor, coachism, or any
    mode can be: serious | chaotic | balanced
    """
    import random

    # 1% chance to drop a legendary easter egg
    if random.random() < 0.01:
        return random.choice(LEGENDARY)

    # Category bias
    if kind == "motivational":
        return random.choice(MOTIVATIONAL)
    elif kind == "silly":
        return random.choice(SILLY)
    elif kind == "portmanteau":
        return random.choice(PORTMANTEAUS)
    elif kind == "metaphor":
        return random.choice(METAPHORS)
    elif kind == "coachism":
        return random.choice(COACHISMS)
    else:
        # Mode tweaks
        if mode == "serious":
            return random.choice(MOTIVATIONAL + COACHISMS)
        elif mode == "chaotic":
            return random.choice(SILLY + PORTMANTEAUS + METAPHORS)
        else:  # balanced
            return random.choice(ALL_PHRASES)