name: Pete Reports

on:
  schedule:
    - cron: "0 4 * * *"     # Daily 04:00 UTC, 05:00 UK in summer
    - cron: "0 5 * * *"     # Daily 05:00 UTC, 05:00 UK in winter
    - cron: "0 9 * * 5"     # Friday 09:00 UTC, 10:00 UK in summer
    - cron: "0 10 * * 5"    # Friday 10:00 UTC, 10:00 UK in winter, 11:00 UK in summer
    - cron: "0 14 * * 0"    # Sunday 14:00 UTC, 15:00 UK in summer
    - cron: "0 15 * * 0"    # Sunday 15:00 UTC, 15:00 UK in winter, 16:00 UK in summer
  workflow_dispatch:
    inputs:
      kind:
        description: "Which report to run: d=daily, w=weekly, c=cycle"
        required: true
        default: "d"
        type: choice
        options: [d, w, c]

permissions:
  contents: write

jobs:
  daily:
    if: github.event.schedule == '0 5 * * *' || github.event.schedule == '0 4 * * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.kind == 'd')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Build Knowledge (consolidate Apple, Withings, WGER)
        run: python summaries/build_knowledge.py

      - name: Run Pete Messenger
        run: python integrations/pete_feedback/messenger.py --type daily
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PYTHONPATH: .

  weekly:
    if: github.event.schedule == '0 10 * * 5' || github.event.schedule == '0 9 * * 5' || (github.event_name == 'workflow_dispatch' && github.event.inputs.kind == 'w')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Build Knowledge
        run: python summaries/build_knowledge.py

      - name: Run Pete Messenger
        run: python integrations/pete_feedback/messenger.py --type weekly
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PYTHONPATH: .

  cycle:
    if: github.event.schedule == '0 15 * * 0' || github.event.schedule == '0 14 * * 0' || (github.event_name == 'workflow_dispatch' && github.event.inputs.kind == 'c')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Build Knowledge
        run: python summaries/build_knowledge.py

      - name: Run Pete Messenger
        run: python integrations/pete_feedback/messenger.py --type cycle
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PYTHONPATH: .
