name: Pete Cycle Review

on:
  schedule:
    - cron: "0 15 * * 0"   # Sundays at 15:00 UTC
  workflow_dispatch:

jobs:
  cycle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python integrations/pete_feedback/messenger.py --type cycle
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}