# DEPRECATED: superseded by wger_cycle.yml

Name: Apply Wger Plan (on push)

on:
  push:
    paths:
      - "integrations/wger/plans/*.json"
      - "integrations/wger/routine_builder.py"
workflow_dispatch:
   inputs:
      plan:
        description: "Optional path to a specific plan JSON"
        required: false
        default: ""

jiobs:
  apply:
    runs-on: ubuntu-latest
    env:
      WGER_API_KEY: ${{ secrets.WGER_API_KEY }}
      WGER_BASE_URL: https://wger.de/api/v2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install --upgrade requests

      - name: Determine plan file
        id: plan
        shell: bash
        run: |
          set -e
          if [ -n "${{ github.event.inputs.plan }}" ]; then
            PLAN="${{ github.event.inputs.plan }}"
          else
            PLAN=$(ls -1 integrations/wger/plans/plan_*.json | sort | tail -n 1)
          fi
          echo "PLAN=$PLAN" >> $GITHUB_ENV
          echo "Using PLAN=$PLAN"
      
      - name: Apply plan to wger
        shell: bash
        run: |
          set -e
          echo "[wger] Base URL: ${WGER_BASE_URL}"
          echo "[wger] Dry run: NO"
          echo "[wger] Reading plan: ${PLAN}"
          python integrations/wger/routine_builder.py "${PLAN}"