name: Wger Cycle

on:
  schedule:
    - cron: "0 15 */28 * 0" # Every 4th Sunday at 15:00 UTC (3Pm)
  workflow_dispatch:

defaults:
  run-plannect-block: |
    python integrations/wger/plan_next_block.py

  upload-plan: |
    python integrations/wger/wger_uploads.py

  send-telegram: |
    curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage  \
    -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
    -d text="📡 New 4-week Warkout plan generated and uploaded successfully! "
