name: Wger Cycle Review

on:
  schedule:
    - cron: "0 15 * * 0"   # Sundays at 15:00 UTC
  workflow_dispatch:

jobs:
  cycle-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Pete’s Cycle Narrative
        id: pete
        run: |
          msg=$(python - <<'PY'
          from integrations.pete_feedback.narrative_builder import build_cycle_narrative
          import json, pathlib
          metrics_path = pathlib.Path("docs/analytics/unified_metrics.json")
          metrics = {}
          if metrics_path.exists():
              metrics = json.loads(metrics_path.read_text())
          print(build_cycle_narrative(metrics))
          PY
          )
          echo "msg=$msg" >> $GITHUB_OUTPUT

      - name: Send Telegram Message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="${{ steps.pete.outputs.msg }}"

      - name: Commit Updates
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          phrase=$(python - <<'PY'
          from integrations.pete_feedback.catchphrases import random_phrase
          print(random_phrase(kind="metaphor", mode="chaotic"))
          PY
          )
          git add summaries/cycle/* knowledge/* integrations/wger/logs/* docs/analytics/*
          git commit -m "Pete’s gainz gospel 🚀 | $phrase (Cycle sync $(date -u +%Y-%m-%d))" || echo "No changes to commit"
          git push