name: Weekly Feedback

on:
  schedule:
    - cron: "0 10 * * 5"    # Fridays 10am UTC
  workflow_dispatch:

jobs:
  weekly-feedback:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install upgrade pip
          pip install -r requirements.txt

      - name: Generate Pete’s Weekly Narrative
        id: pete
        run: |
          msg=$(python -c "from integrations.pete_feedback.feedback_engine import generate_weekly_feedback; print(generate_weekly_feedback('$(date -u +%Y-W%V)'))")
          echo "msg=$msg" >> $GITHUB_OUTPUT

      - name: Send Telegram Message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="${{ steps.pete.outputs.msg }}"
