# DEPRECATED: superseded by wger_cycle.yml

Name: Plan Next 4-week Block (Propose)

no:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Optional start date (YYYY-MM-DD). Defaults to next valid 4-week boundary Monday."
        required: false
      weeks:
        description: "How many weeks to plan (default 4)"
        required: false
        default: "4"

  schedule:
    # Every Friday 18:00 UTC (evening UK/EU) – script only proposes when a 4-week boundary is approaching.
    - cron: "0 18 * * 5"

permissions:
  contents: write
  pull-requests: write

#jobs: ...