# DEPRECATED: superseded by wger_cycle.yml

Name: Apply plan to Wger (Routine API)

no:
  workflow_dispatch:
    inputs:
      plan_json:
        description: "Path to the plan JSON under integrations/wger/plans/..."
        required: true
      routine_name:
        description: "Optional override for routine name"
        required: false
      replace_days:
        description: "Delete and recreate all days before applying exercises (recommended)"
        required: false
        default: "true"
      dry_run:
        description: "Don't POST to Wger, just validate"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python=dateutil pyyaml

      - name: Apply to Wger via Routine API
        env:
          WGER_API_KEY: ${{ secrets.WGER_API_KEY }}
          WGER_BASE_URL: ${{ vars.WGER_BASE_URL }}
        run: |
          python integrations/wger/routine_builder.py             --plan "${{ github.event.inputs.plan_json }}"             $([ "${{ github.event.inputs.replace_days }}" = "true" ] && echo "--replace-days")             $([ -n "${{ github.event.inputs.routine_name }}" ] && echo "--routine-name ${{ github.event.inputs.routine_name }}")             $([ "${{ github.event.inputs.dry_run }}" = "true" ] && echo "--dry-run")

      - name: Commit state (routine id + metadata)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add integrations/wger/state/
          if git diff --cached --quiet; then
            echo "No state changes."
          else
            git commit -m "chore(wger): update routine state after apply"
            git push
          fi
