name: Wger Weekly Check-in

on:
  schedule:
    - cron: "0 10 * * 5"   # Fridays at 10:00 UTC
  workflow_dispatch:

jobs:
  weekly-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Pete’s Weekly Narrative
        id: pete
        run: |
          msg=$(python - <<'PY'
          from integrations.pete_feedback.narrative_builder import build_weekly_narrative
          from integrations.pete_feedback.catchphrases import random_phrase
          import json, pathlib, random

          metrics_path = pathlib.Path("docs/analytics/unified_metrics.json")
          metrics = {}
          if metrics_path.exists():
              metrics = json.loads(metrics_path.read_text())

          base = build_weekly_narrative(metrics)
          extras = "\n".join(random_phrase() for _ in range(random.randint(1, 2)))
          print(f"{base}\n\n{extras}")
          PY
          )
          echo "msg=$msg" >> $GITHUB_OUTPUT

      - name: Send Telegram Message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="${{ steps.pete.outputs.msg }}"

      - name: Commit Updates
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          phrase=$(python - <<'PY'
          from integrations.pete_feedback.catchphrases import random_phrase
          print(random_phrase())
          PY
          )
          git add summaries/weekly/* knowledge/* integrations/wger/logs/* docs/analytics/*
          git commit -m "Pete’s flex files 📅 | $phrase (Weekly sync $(date -u +%Y-%m-%d))" || echo "No changes to commit"
          git push